### ISSUE TITLE
Instructor Feedback on index.jsp and related code

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Amatheia/TeamProject#1]
- [x] Write your demo (index.jsp) as if you were a consumer of the service. A consumer would not have access to the actual DAOs [here](foodexpirationservice/src/main/webapp/index.jsp#L1-L2). Instead, you should use a call to the service to populate these dropdowns. You could use jQuery/javascript to do this. Consider searching (googling): "how to call a web service to populated a drop-down" for examples.
- [x] This form submission appears to call a servlet (/searchCategory) rather than a rest service.  Again, remember that a consumer won't have access to the form action like [this](https://github.com/Amatheia/TeamProject/blob/master/foodexpirationservice/src/main/webapp/index.jsp#L18), but should instead submit the form to the service.  An example: http://www.mkyong.com/webservices/jax-rs/jax-rs-formparam-example/. Note that rather than posting to rest/user/add you would use http://yourserviceurl/rest/user/add.

**Comment by Amatheia** [comment]
Awesome! Thank you!
